### ISSUE TITLE
Prepare meta-metamodel for migration to src/main

### ISSUE THREAD

**Issue by pvojtechovsky** [INRIA/spoon#1888]
TODOs:
* [ ] check documentation of MetamodelConcept / MetamodelRole
* [ ] check public methods of MetamodelConcept / MetamodelRole
* [ ] look at MMMethod

The matching algorithm of #1686 needs to know whether property of a class is derived or not.
I mean method like
`boolean isDerived(Class<? extends CtElement> clazz, CtRole role);`
It needs to know it in runtime - not in test. 
The question is which Spoon code will deliver that information?
Do we have some meta data storage, which would be available in runtime too?
Do you see other meta model attributes which might be interesting too?

The optional solution would be to implement a new kind of scanner, which would visit not only CtElement based attributes, but also primitive attributes (String, boolean, ...) - it would visit not derived attributes only.

Any suggestions?

**Comment by monperrus** [comment]
It seems we already have this information in annotations `PropertyGetter` and `DerivedProperty`.

This information is available at runtime since `RetentionPolicy.RUNTIME`.

> ` boolean isDerived(Class<? extends CtElement> clazz, CtRole role)`

I don't understand completely. Do you mean that this method is static? If put in `CtElement`, we would have `boolean CtElement#isDerived(CtRole role)`?

**Comment by pvojtechovsky** [comment]
You are right. There is a way how to get this information in runtime, but it is actually quite complicated.
See `MMField#isDerived`, which is actually the only algorithm in spoon, which I know, which does that computation correctly.

I would prefer a spoon runtime meta model API, which would deliver such information in fast and reliable way.

> CtElement#isDerived(CtRole)

would be near to what I am looking for. But I would prefer a method which doesn't need a instance of CtElement.

For example: `MetaModel#isDerived(Class<? extends CtElement>, CtRole)`

WDYT?

**Comment by monperrus** [comment]
> For example: |MetaModel#isDerived(Class<? extends CtElement>, CtRole)|
>
|LGTM|

**Comment by monperrus** [comment]
I propose to call it `isDerivedRoleInClass(CtRole,Class)`

**Comment by pvojtechovsky** [comment]
Thanks for answer. I will make a PR with some similar solution

**Comment by monperrus** [comment]
* [ ] check documentation of MetamodelConcept / MetamodelRole
* [ ] check public methods of MetamodelConcept / MetamodelRole
* [ ] look at MMMethod

**Comment by pvojtechovsky** [comment]
The building of Spoon metamodel in runtime will need some seconds. Optionally we can have generated metamodel (like in #1686), which is very fast to create, but which has to be manually updated whenever Spoon metamodel changes - the consistency is assured by tests.

Which way we go?
A) the spoon start up will need few seconds more to create metamodel
B) the change in metamodel will need manual change in runtime metamodel too
C) ?

**Comment by monperrus** [comment]
I prefer A) because:

1. It's less error-prone
2. In most cases, one does not use the runtime metamodel
3. Spoon is not meant to be used in real time settings

**Comment by pvojtechovsky** [comment]
fixed by #2016
